name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze visionOS target
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -project "Demo App.xcodeproj" -scheme "Demo App Vision" -destination "platform=visionOS Simulator,name=Apple Vision Pro,OS=latest" clean build CODE_SIGNING_ALLOWED=NO
